export const SAVE_POSTIT_SUCCESS = 'SAVE_POSTIT_SUCCESS'
export const EDIT_POSTIT_SUCCESS = 'EDIT_POSTIT_SUCCESS'
export const DELETE_POSTIT_SUCCESS = 'DELETE_POSTIT_SUCCESS'
export const FETCH_POSTITS_SUCCESS = 'FETCH_POSTITS_SUCCESS'