export const SAVE_POSTIT_REQUEST = 'SAVE_POSTIT_REQUEST'
export const EDIT_POSTIT_REQUEST = 'EDIT_POSTIT_REQUEST'
export const DELETE_POSTIT_REQUEST = 'DELETE_POSTIT_REQUEST'
export const FETCH_POSTITS_REQUEST = 'FETCH_POSTITS_REQUEST'

export const SAVE_POSTIT_SUCCESS = 'SAVE_POSTIT_SUCCESS'
export const EDIT_POSTIT_SUCCESS = 'EDIT_POSTIT_SUCCESS'
export const DELETE_POSTIT_SUCCESS = 'DELETE_POSTIT_SUCCESS'
export const FETCH_POSTITS_SUCCESS = 'FETCH_POSTITS_SUCCESS'

export const SAVE_POSTIT_FAILURE = 'SAVE_POSTIT_FAILURE'
export const EDIT_POSTIT_FAILURE = 'EDIT_POSTIT_FAILURE'
export const DELETE_POSTIT_FAILURE = 'DELETE_POSTIT_FAILURE'
export const FETCH_POSTITS_FAILURE = 'FETCH_POSTITS_FAILURE'